
FROM mysql:8.0

WORKDIR /docker-entrypoint-initdb.d

# Copy the SQL file(s) or script(s) to initialize the database
COPY ./mysql/init.sql .


# Set environment variables
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=bookdb
ENV MYSQL_USER=bookuser
ENV MYSQL_PASSWORD=bookuserpassword

# Expose port 3306
EXPOSE 3306